version: '3.8'

services:
  db:
    image: postgres:16-alpine
    container_name: gophkeeper-postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: gophkeeper
      POSTGRES_HOST_AUTH_METHOD: trust
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: