// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: auth.proto

package gophkeeper

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RegisterRequest struct {
	state               protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Email    string                 `protobuf:"bytes,1,opt,name=email,proto3"`
	xxx_hidden_Password string                 `protobuf:"bytes,2,opt,name=password,proto3"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *RegisterRequest) Reset() {
	*x = RegisterRequest{}
	mi := &file_auth_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterRequest) ProtoMessage() {}

func (x *RegisterRequest) ProtoReflect() protoreflect.Message {
	mi := &file_auth_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *RegisterRequest) GetEmail() string {
	if x != nil {
		return x.xxx_hidden_Email
	}
	return ""
}

func (x *RegisterRequest) GetPassword() string {
	if x != nil {
		return x.xxx_hidden_Password
	}
	return ""
}

func (x *RegisterRequest) SetEmail(v string) {
	x.xxx_hidden_Email = v
}

func (x *RegisterRequest) SetPassword(v string) {
	x.xxx_hidden_Password = v
}

type RegisterRequest_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Email    string
	Password string
}

func (b0 RegisterRequest_builder) Build() *RegisterRequest {
	m0 := &RegisterRequest{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Email = b.Email
	x.xxx_hidden_Password = b.Password
	return m0
}

type RegisterResponse struct {
	state              protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_UserId  string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3"`
	xxx_hidden_Message string                 `protobuf:"bytes,2,opt,name=message,proto3"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *RegisterResponse) Reset() {
	*x = RegisterResponse{}
	mi := &file_auth_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterResponse) ProtoMessage() {}

func (x *RegisterResponse) ProtoReflect() protoreflect.Message {
	mi := &file_auth_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *RegisterResponse) GetUserId() string {
	if x != nil {
		return x.xxx_hidden_UserId
	}
	return ""
}

func (x *RegisterResponse) GetMessage() string {
	if x != nil {
		return x.xxx_hidden_Message
	}
	return ""
}

func (x *RegisterResponse) SetUserId(v string) {
	x.xxx_hidden_UserId = v
}

func (x *RegisterResponse) SetMessage(v string) {
	x.xxx_hidden_Message = v
}

type RegisterResponse_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	UserId  string
	Message string
}

func (b0 RegisterResponse_builder) Build() *RegisterResponse {
	m0 := &RegisterResponse{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_UserId = b.UserId
	x.xxx_hidden_Message = b.Message
	return m0
}

type LoginPasswordRequest struct {
	state               protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Email    string                 `protobuf:"bytes,1,opt,name=email,proto3"`
	xxx_hidden_Password string                 `protobuf:"bytes,2,opt,name=password,proto3"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *LoginPasswordRequest) Reset() {
	*x = LoginPasswordRequest{}
	mi := &file_auth_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoginPasswordRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginPasswordRequest) ProtoMessage() {}

func (x *LoginPasswordRequest) ProtoReflect() protoreflect.Message {
	mi := &file_auth_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *LoginPasswordRequest) GetEmail() string {
	if x != nil {
		return x.xxx_hidden_Email
	}
	return ""
}

func (x *LoginPasswordRequest) GetPassword() string {
	if x != nil {
		return x.xxx_hidden_Password
	}
	return ""
}

func (x *LoginPasswordRequest) SetEmail(v string) {
	x.xxx_hidden_Email = v
}

func (x *LoginPasswordRequest) SetPassword(v string) {
	x.xxx_hidden_Password = v
}

type LoginPasswordRequest_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Email    string
	Password string
}

func (b0 LoginPasswordRequest_builder) Build() *LoginPasswordRequest {
	m0 := &LoginPasswordRequest{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Email = b.Email
	x.xxx_hidden_Password = b.Password
	return m0
}

type LoginOAuthRequest struct {
	state               protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Provider string                 `protobuf:"bytes,1,opt,name=provider,proto3"`
	xxx_hidden_Code     string                 `protobuf:"bytes,2,opt,name=code,proto3"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *LoginOAuthRequest) Reset() {
	*x = LoginOAuthRequest{}
	mi := &file_auth_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoginOAuthRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginOAuthRequest) ProtoMessage() {}

func (x *LoginOAuthRequest) ProtoReflect() protoreflect.Message {
	mi := &file_auth_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *LoginOAuthRequest) GetProvider() string {
	if x != nil {
		return x.xxx_hidden_Provider
	}
	return ""
}

func (x *LoginOAuthRequest) GetCode() string {
	if x != nil {
		return x.xxx_hidden_Code
	}
	return ""
}

func (x *LoginOAuthRequest) SetProvider(v string) {
	x.xxx_hidden_Provider = v
}

func (x *LoginOAuthRequest) SetCode(v string) {
	x.xxx_hidden_Code = v
}

type LoginOAuthRequest_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Provider string
	Code     string
}

func (b0 LoginOAuthRequest_builder) Build() *LoginOAuthRequest {
	m0 := &LoginOAuthRequest{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Provider = b.Provider
	x.xxx_hidden_Code = b.Code
	return m0
}

type LoginResponse struct {
	state              protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Token   string                 `protobuf:"bytes,1,opt,name=token,proto3"`
	xxx_hidden_UserId  string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3"`
	xxx_hidden_Message string                 `protobuf:"bytes,3,opt,name=message,proto3"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *LoginResponse) Reset() {
	*x = LoginResponse{}
	mi := &file_auth_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoginResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginResponse) ProtoMessage() {}

func (x *LoginResponse) ProtoReflect() protoreflect.Message {
	mi := &file_auth_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *LoginResponse) GetToken() string {
	if x != nil {
		return x.xxx_hidden_Token
	}
	return ""
}

func (x *LoginResponse) GetUserId() string {
	if x != nil {
		return x.xxx_hidden_UserId
	}
	return ""
}

func (x *LoginResponse) GetMessage() string {
	if x != nil {
		return x.xxx_hidden_Message
	}
	return ""
}

func (x *LoginResponse) SetToken(v string) {
	x.xxx_hidden_Token = v
}

func (x *LoginResponse) SetUserId(v string) {
	x.xxx_hidden_UserId = v
}

func (x *LoginResponse) SetMessage(v string) {
	x.xxx_hidden_Message = v
}

type LoginResponse_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Token   string
	UserId  string
	Message string
}

func (b0 LoginResponse_builder) Build() *LoginResponse {
	m0 := &LoginResponse{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Token = b.Token
	x.xxx_hidden_UserId = b.UserId
	x.xxx_hidden_Message = b.Message
	return m0
}

type GetOAuthURLRequest struct {
	state               protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Provider string                 `protobuf:"bytes,1,opt,name=provider,proto3"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *GetOAuthURLRequest) Reset() {
	*x = GetOAuthURLRequest{}
	mi := &file_auth_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetOAuthURLRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetOAuthURLRequest) ProtoMessage() {}

func (x *GetOAuthURLRequest) ProtoReflect() protoreflect.Message {
	mi := &file_auth_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *GetOAuthURLRequest) GetProvider() string {
	if x != nil {
		return x.xxx_hidden_Provider
	}
	return ""
}

func (x *GetOAuthURLRequest) SetProvider(v string) {
	x.xxx_hidden_Provider = v
}

type GetOAuthURLRequest_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Provider string
}

func (b0 GetOAuthURLRequest_builder) Build() *GetOAuthURLRequest {
	m0 := &GetOAuthURLRequest{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Provider = b.Provider
	return m0
}

type GetOAuthURLResponse struct {
	state              protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_AuthUrl string                 `protobuf:"bytes,1,opt,name=auth_url,json=authUrl,proto3"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *GetOAuthURLResponse) Reset() {
	*x = GetOAuthURLResponse{}
	mi := &file_auth_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetOAuthURLResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetOAuthURLResponse) ProtoMessage() {}

func (x *GetOAuthURLResponse) ProtoReflect() protoreflect.Message {
	mi := &file_auth_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *GetOAuthURLResponse) GetAuthUrl() string {
	if x != nil {
		return x.xxx_hidden_AuthUrl
	}
	return ""
}

func (x *GetOAuthURLResponse) SetAuthUrl(v string) {
	x.xxx_hidden_AuthUrl = v
}

type GetOAuthURLResponse_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	AuthUrl string
}

func (b0 GetOAuthURLResponse_builder) Build() *GetOAuthURLResponse {
	m0 := &GetOAuthURLResponse{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_AuthUrl = b.AuthUrl
	return m0
}

var File_auth_proto protoreflect.FileDescriptor

const file_auth_proto_rawDesc = "" +
	"\n" +
	"\n" +
	"auth.proto\x12\n" +
	"gophkeeper\"C\n" +
	"\x0fRegisterRequest\x12\x14\n" +
	"\x05email\x18\x01 \x01(\tR\x05email\x12\x1a\n" +
	"\bpassword\x18\x02 \x01(\tR\bpassword\"E\n" +
	"\x10RegisterResponse\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"H\n" +
	"\x14LoginPasswordRequest\x12\x14\n" +
	"\x05email\x18\x01 \x01(\tR\x05email\x12\x1a\n" +
	"\bpassword\x18\x02 \x01(\tR\bpassword\"C\n" +
	"\x11LoginOAuthRequest\x12\x1a\n" +
	"\bprovider\x18\x01 \x01(\tR\bprovider\x12\x12\n" +
	"\x04code\x18\x02 \x01(\tR\x04code\"X\n" +
	"\rLoginResponse\x12\x14\n" +
	"\x05token\x18\x01 \x01(\tR\x05token\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage\"0\n" +
	"\x12GetOAuthURLRequest\x12\x1a\n" +
	"\bprovider\x18\x01 \x01(\tR\bprovider\"0\n" +
	"\x13GetOAuthURLResponse\x12\x19\n" +
	"\bauth_url\x18\x01 \x01(\tR\aauthUrl2\xba\x02\n" +
	"\vAuthService\x12E\n" +
	"\bRegister\x12\x1b.gophkeeper.RegisterRequest\x1a\x1c.gophkeeper.RegisterResponse\x12L\n" +
	"\rLoginPassword\x12 .gophkeeper.LoginPasswordRequest\x1a\x19.gophkeeper.LoginResponse\x12F\n" +
	"\n" +
	"LoginOAuth\x12\x1d.gophkeeper.LoginOAuthRequest\x1a\x19.gophkeeper.LoginResponse\x12N\n" +
	"\vGetOAuthURL\x12\x1e.gophkeeper.GetOAuthURLRequest\x1a\x1f.gophkeeper.GetOAuthURLResponseB$Z\"gophkeeper/server/proto/gophkeeperb\x06proto3"

var file_auth_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_auth_proto_goTypes = []any{
	(*RegisterRequest)(nil),      // 0: gophkeeper.RegisterRequest
	(*RegisterResponse)(nil),     // 1: gophkeeper.RegisterResponse
	(*LoginPasswordRequest)(nil), // 2: gophkeeper.LoginPasswordRequest
	(*LoginOAuthRequest)(nil),    // 3: gophkeeper.LoginOAuthRequest
	(*LoginResponse)(nil),        // 4: gophkeeper.LoginResponse
	(*GetOAuthURLRequest)(nil),   // 5: gophkeeper.GetOAuthURLRequest
	(*GetOAuthURLResponse)(nil),  // 6: gophkeeper.GetOAuthURLResponse
}
var file_auth_proto_depIdxs = []int32{
	0, // 0: gophkeeper.AuthService.Register:input_type -> gophkeeper.RegisterRequest
	2, // 1: gophkeeper.AuthService.LoginPassword:input_type -> gophkeeper.LoginPasswordRequest
	3, // 2: gophkeeper.AuthService.LoginOAuth:input_type -> gophkeeper.LoginOAuthRequest
	5, // 3: gophkeeper.AuthService.GetOAuthURL:input_type -> gophkeeper.GetOAuthURLRequest
	1, // 4: gophkeeper.AuthService.Register:output_type -> gophkeeper.RegisterResponse
	4, // 5: gophkeeper.AuthService.LoginPassword:output_type -> gophkeeper.LoginResponse
	4, // 6: gophkeeper.AuthService.LoginOAuth:output_type -> gophkeeper.LoginResponse
	6, // 7: gophkeeper.AuthService.GetOAuthURL:output_type -> gophkeeper.GetOAuthURLResponse
	4, // [4:8] is the sub-list for method output_type
	0, // [0:4] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_auth_proto_init() }
func file_auth_proto_init() {
	if File_auth_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_auth_proto_rawDesc), len(file_auth_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_auth_proto_goTypes,
		DependencyIndexes: file_auth_proto_depIdxs,
		MessageInfos:      file_auth_proto_msgTypes,
	}.Build()
	File_auth_proto = out.File
	file_auth_proto_goTypes = nil
	file_auth_proto_depIdxs = nil
}
