// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: secret.proto

package gophkeeper

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CreateSecretRequest struct {
	state               protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Type     string                 `protobuf:"bytes,1,opt,name=type,proto3"`
	xxx_hidden_Title    string                 `protobuf:"bytes,2,opt,name=title,proto3"`
	xxx_hidden_Data     string                 `protobuf:"bytes,3,opt,name=data,proto3"`
	xxx_hidden_Metadata string                 `protobuf:"bytes,4,opt,name=metadata,proto3"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *CreateSecretRequest) Reset() {
	*x = CreateSecretRequest{}
	mi := &file_secret_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateSecretRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateSecretRequest) ProtoMessage() {}

func (x *CreateSecretRequest) ProtoReflect() protoreflect.Message {
	mi := &file_secret_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *CreateSecretRequest) GetType() string {
	if x != nil {
		return x.xxx_hidden_Type
	}
	return ""
}

func (x *CreateSecretRequest) GetTitle() string {
	if x != nil {
		return x.xxx_hidden_Title
	}
	return ""
}

func (x *CreateSecretRequest) GetData() string {
	if x != nil {
		return x.xxx_hidden_Data
	}
	return ""
}

func (x *CreateSecretRequest) GetMetadata() string {
	if x != nil {
		return x.xxx_hidden_Metadata
	}
	return ""
}

func (x *CreateSecretRequest) SetType(v string) {
	x.xxx_hidden_Type = v
}

func (x *CreateSecretRequest) SetTitle(v string) {
	x.xxx_hidden_Title = v
}

func (x *CreateSecretRequest) SetData(v string) {
	x.xxx_hidden_Data = v
}

func (x *CreateSecretRequest) SetMetadata(v string) {
	x.xxx_hidden_Metadata = v
}

type CreateSecretRequest_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Type     string
	Title    string
	Data     string
	Metadata string
}

func (b0 CreateSecretRequest_builder) Build() *CreateSecretRequest {
	m0 := &CreateSecretRequest{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Type = b.Type
	x.xxx_hidden_Title = b.Title
	x.xxx_hidden_Data = b.Data
	x.xxx_hidden_Metadata = b.Metadata
	return m0
}

type CreateSecretResponse struct {
	state               protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_SecretId string                 `protobuf:"bytes,1,opt,name=secret_id,json=secretId,proto3"`
	xxx_hidden_Message  string                 `protobuf:"bytes,2,opt,name=message,proto3"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *CreateSecretResponse) Reset() {
	*x = CreateSecretResponse{}
	mi := &file_secret_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateSecretResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateSecretResponse) ProtoMessage() {}

func (x *CreateSecretResponse) ProtoReflect() protoreflect.Message {
	mi := &file_secret_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *CreateSecretResponse) GetSecretId() string {
	if x != nil {
		return x.xxx_hidden_SecretId
	}
	return ""
}

func (x *CreateSecretResponse) GetMessage() string {
	if x != nil {
		return x.xxx_hidden_Message
	}
	return ""
}

func (x *CreateSecretResponse) SetSecretId(v string) {
	x.xxx_hidden_SecretId = v
}

func (x *CreateSecretResponse) SetMessage(v string) {
	x.xxx_hidden_Message = v
}

type CreateSecretResponse_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	SecretId string
	Message  string
}

func (b0 CreateSecretResponse_builder) Build() *CreateSecretResponse {
	m0 := &CreateSecretResponse{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_SecretId = b.SecretId
	x.xxx_hidden_Message = b.Message
	return m0
}

type GetSecretsRequest struct {
	state         protoimpl.MessageState `protogen:"opaque.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSecretsRequest) Reset() {
	*x = GetSecretsRequest{}
	mi := &file_secret_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSecretsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSecretsRequest) ProtoMessage() {}

func (x *GetSecretsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_secret_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

type GetSecretsRequest_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

}

func (b0 GetSecretsRequest_builder) Build() *GetSecretsRequest {
	m0 := &GetSecretsRequest{}
	b, x := &b0, m0
	_, _ = b, x
	return m0
}

type GetSecretsResponse struct {
	state              protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Secrets *[]*SecretData         `protobuf:"bytes,1,rep,name=secrets,proto3"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *GetSecretsResponse) Reset() {
	*x = GetSecretsResponse{}
	mi := &file_secret_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSecretsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSecretsResponse) ProtoMessage() {}

func (x *GetSecretsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_secret_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *GetSecretsResponse) GetSecrets() []*SecretData {
	if x != nil {
		if x.xxx_hidden_Secrets != nil {
			return *x.xxx_hidden_Secrets
		}
	}
	return nil
}

func (x *GetSecretsResponse) SetSecrets(v []*SecretData) {
	x.xxx_hidden_Secrets = &v
}

type GetSecretsResponse_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Secrets []*SecretData
}

func (b0 GetSecretsResponse_builder) Build() *GetSecretsResponse {
	m0 := &GetSecretsResponse{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Secrets = &b.Secrets
	return m0
}

type GetSecretRequest struct {
	state               protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_SecretId string                 `protobuf:"bytes,1,opt,name=secret_id,json=secretId,proto3"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *GetSecretRequest) Reset() {
	*x = GetSecretRequest{}
	mi := &file_secret_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSecretRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSecretRequest) ProtoMessage() {}

func (x *GetSecretRequest) ProtoReflect() protoreflect.Message {
	mi := &file_secret_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *GetSecretRequest) GetSecretId() string {
	if x != nil {
		return x.xxx_hidden_SecretId
	}
	return ""
}

func (x *GetSecretRequest) SetSecretId(v string) {
	x.xxx_hidden_SecretId = v
}

type GetSecretRequest_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	SecretId string
}

func (b0 GetSecretRequest_builder) Build() *GetSecretRequest {
	m0 := &GetSecretRequest{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_SecretId = b.SecretId
	return m0
}

type GetSecretResponse struct {
	state             protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Secret *SecretData            `protobuf:"bytes,1,opt,name=secret,proto3"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *GetSecretResponse) Reset() {
	*x = GetSecretResponse{}
	mi := &file_secret_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSecretResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSecretResponse) ProtoMessage() {}

func (x *GetSecretResponse) ProtoReflect() protoreflect.Message {
	mi := &file_secret_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *GetSecretResponse) GetSecret() *SecretData {
	if x != nil {
		return x.xxx_hidden_Secret
	}
	return nil
}

func (x *GetSecretResponse) SetSecret(v *SecretData) {
	x.xxx_hidden_Secret = v
}

func (x *GetSecretResponse) HasSecret() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Secret != nil
}

func (x *GetSecretResponse) ClearSecret() {
	x.xxx_hidden_Secret = nil
}

type GetSecretResponse_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Secret *SecretData
}

func (b0 GetSecretResponse_builder) Build() *GetSecretResponse {
	m0 := &GetSecretResponse{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Secret = b.Secret
	return m0
}

type DeleteSecretRequest struct {
	state               protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_SecretId string                 `protobuf:"bytes,1,opt,name=secret_id,json=secretId,proto3"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *DeleteSecretRequest) Reset() {
	*x = DeleteSecretRequest{}
	mi := &file_secret_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteSecretRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteSecretRequest) ProtoMessage() {}

func (x *DeleteSecretRequest) ProtoReflect() protoreflect.Message {
	mi := &file_secret_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *DeleteSecretRequest) GetSecretId() string {
	if x != nil {
		return x.xxx_hidden_SecretId
	}
	return ""
}

func (x *DeleteSecretRequest) SetSecretId(v string) {
	x.xxx_hidden_SecretId = v
}

type DeleteSecretRequest_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	SecretId string
}

func (b0 DeleteSecretRequest_builder) Build() *DeleteSecretRequest {
	m0 := &DeleteSecretRequest{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_SecretId = b.SecretId
	return m0
}

type DeleteSecretResponse struct {
	state              protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Message string                 `protobuf:"bytes,1,opt,name=message,proto3"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *DeleteSecretResponse) Reset() {
	*x = DeleteSecretResponse{}
	mi := &file_secret_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteSecretResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteSecretResponse) ProtoMessage() {}

func (x *DeleteSecretResponse) ProtoReflect() protoreflect.Message {
	mi := &file_secret_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *DeleteSecretResponse) GetMessage() string {
	if x != nil {
		return x.xxx_hidden_Message
	}
	return ""
}

func (x *DeleteSecretResponse) SetMessage(v string) {
	x.xxx_hidden_Message = v
}

type DeleteSecretResponse_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Message string
}

func (b0 DeleteSecretResponse_builder) Build() *DeleteSecretResponse {
	m0 := &DeleteSecretResponse{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Message = b.Message
	return m0
}

// Общая структура секрета
type SecretData struct {
	state                protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Id        string                 `protobuf:"bytes,1,opt,name=id,proto3"`
	xxx_hidden_UserId    string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3"`
	xxx_hidden_Type      string                 `protobuf:"bytes,3,opt,name=type,proto3"`
	xxx_hidden_Title     string                 `protobuf:"bytes,4,opt,name=title,proto3"`
	xxx_hidden_Data      string                 `protobuf:"bytes,5,opt,name=data,proto3"`
	xxx_hidden_Metadata  string                 `protobuf:"bytes,6,opt,name=metadata,proto3"`
	xxx_hidden_CreatedAt string                 `protobuf:"bytes,7,opt,name=created_at,json=createdAt,proto3"`
	xxx_hidden_UpdatedAt string                 `protobuf:"bytes,8,opt,name=updated_at,json=updatedAt,proto3"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *SecretData) Reset() {
	*x = SecretData{}
	mi := &file_secret_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SecretData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SecretData) ProtoMessage() {}

func (x *SecretData) ProtoReflect() protoreflect.Message {
	mi := &file_secret_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *SecretData) GetId() string {
	if x != nil {
		return x.xxx_hidden_Id
	}
	return ""
}

func (x *SecretData) GetUserId() string {
	if x != nil {
		return x.xxx_hidden_UserId
	}
	return ""
}

func (x *SecretData) GetType() string {
	if x != nil {
		return x.xxx_hidden_Type
	}
	return ""
}

func (x *SecretData) GetTitle() string {
	if x != nil {
		return x.xxx_hidden_Title
	}
	return ""
}

func (x *SecretData) GetData() string {
	if x != nil {
		return x.xxx_hidden_Data
	}
	return ""
}

func (x *SecretData) GetMetadata() string {
	if x != nil {
		return x.xxx_hidden_Metadata
	}
	return ""
}

func (x *SecretData) GetCreatedAt() string {
	if x != nil {
		return x.xxx_hidden_CreatedAt
	}
	return ""
}

func (x *SecretData) GetUpdatedAt() string {
	if x != nil {
		return x.xxx_hidden_UpdatedAt
	}
	return ""
}

func (x *SecretData) SetId(v string) {
	x.xxx_hidden_Id = v
}

func (x *SecretData) SetUserId(v string) {
	x.xxx_hidden_UserId = v
}

func (x *SecretData) SetType(v string) {
	x.xxx_hidden_Type = v
}

func (x *SecretData) SetTitle(v string) {
	x.xxx_hidden_Title = v
}

func (x *SecretData) SetData(v string) {
	x.xxx_hidden_Data = v
}

func (x *SecretData) SetMetadata(v string) {
	x.xxx_hidden_Metadata = v
}

func (x *SecretData) SetCreatedAt(v string) {
	x.xxx_hidden_CreatedAt = v
}

func (x *SecretData) SetUpdatedAt(v string) {
	x.xxx_hidden_UpdatedAt = v
}

type SecretData_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Id        string
	UserId    string
	Type      string
	Title     string
	Data      string
	Metadata  string
	CreatedAt string
	UpdatedAt string
}

func (b0 SecretData_builder) Build() *SecretData {
	m0 := &SecretData{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Id = b.Id
	x.xxx_hidden_UserId = b.UserId
	x.xxx_hidden_Type = b.Type
	x.xxx_hidden_Title = b.Title
	x.xxx_hidden_Data = b.Data
	x.xxx_hidden_Metadata = b.Metadata
	x.xxx_hidden_CreatedAt = b.CreatedAt
	x.xxx_hidden_UpdatedAt = b.UpdatedAt
	return m0
}

var File_secret_proto protoreflect.FileDescriptor

const file_secret_proto_rawDesc = "" +
	"\n" +
	"\fsecret.proto\x12\n" +
	"gophkeeper\"o\n" +
	"\x13CreateSecretRequest\x12\x12\n" +
	"\x04type\x18\x01 \x01(\tR\x04type\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12\x12\n" +
	"\x04data\x18\x03 \x01(\tR\x04data\x12\x1a\n" +
	"\bmetadata\x18\x04 \x01(\tR\bmetadata\"M\n" +
	"\x14CreateSecretResponse\x12\x1b\n" +
	"\tsecret_id\x18\x01 \x01(\tR\bsecretId\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"\x13\n" +
	"\x11GetSecretsRequest\"F\n" +
	"\x12GetSecretsResponse\x120\n" +
	"\asecrets\x18\x01 \x03(\v2\x16.gophkeeper.SecretDataR\asecrets\"/\n" +
	"\x10GetSecretRequest\x12\x1b\n" +
	"\tsecret_id\x18\x01 \x01(\tR\bsecretId\"C\n" +
	"\x11GetSecretResponse\x12.\n" +
	"\x06secret\x18\x01 \x01(\v2\x16.gophkeeper.SecretDataR\x06secret\"2\n" +
	"\x13DeleteSecretRequest\x12\x1b\n" +
	"\tsecret_id\x18\x01 \x01(\tR\bsecretId\"0\n" +
	"\x14DeleteSecretResponse\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\"\xcd\x01\n" +
	"\n" +
	"SecretData\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12\x12\n" +
	"\x04type\x18\x03 \x01(\tR\x04type\x12\x14\n" +
	"\x05title\x18\x04 \x01(\tR\x05title\x12\x12\n" +
	"\x04data\x18\x05 \x01(\tR\x04data\x12\x1a\n" +
	"\bmetadata\x18\x06 \x01(\tR\bmetadata\x12\x1d\n" +
	"\n" +
	"created_at\x18\a \x01(\tR\tcreatedAt\x12\x1d\n" +
	"\n" +
	"updated_at\x18\b \x01(\tR\tupdatedAt2\xcc\x02\n" +
	"\rSecretService\x12Q\n" +
	"\fCreateSecret\x12\x1f.gophkeeper.CreateSecretRequest\x1a .gophkeeper.CreateSecretResponse\x12K\n" +
	"\n" +
	"GetSecrets\x12\x1d.gophkeeper.GetSecretsRequest\x1a\x1e.gophkeeper.GetSecretsResponse\x12H\n" +
	"\tGetSecret\x12\x1c.gophkeeper.GetSecretRequest\x1a\x1d.gophkeeper.GetSecretResponse\x12Q\n" +
	"\fDeleteSecret\x12\x1f.gophkeeper.DeleteSecretRequest\x1a .gophkeeper.DeleteSecretResponseB$Z\"gophkeeper/server/proto/gophkeeperb\x06proto3"

var file_secret_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_secret_proto_goTypes = []any{
	(*CreateSecretRequest)(nil),  // 0: gophkeeper.CreateSecretRequest
	(*CreateSecretResponse)(nil), // 1: gophkeeper.CreateSecretResponse
	(*GetSecretsRequest)(nil),    // 2: gophkeeper.GetSecretsRequest
	(*GetSecretsResponse)(nil),   // 3: gophkeeper.GetSecretsResponse
	(*GetSecretRequest)(nil),     // 4: gophkeeper.GetSecretRequest
	(*GetSecretResponse)(nil),    // 5: gophkeeper.GetSecretResponse
	(*DeleteSecretRequest)(nil),  // 6: gophkeeper.DeleteSecretRequest
	(*DeleteSecretResponse)(nil), // 7: gophkeeper.DeleteSecretResponse
	(*SecretData)(nil),           // 8: gophkeeper.SecretData
}
var file_secret_proto_depIdxs = []int32{
	8, // 0: gophkeeper.GetSecretsResponse.secrets:type_name -> gophkeeper.SecretData
	8, // 1: gophkeeper.GetSecretResponse.secret:type_name -> gophkeeper.SecretData
	0, // 2: gophkeeper.SecretService.CreateSecret:input_type -> gophkeeper.CreateSecretRequest
	2, // 3: gophkeeper.SecretService.GetSecrets:input_type -> gophkeeper.GetSecretsRequest
	4, // 4: gophkeeper.SecretService.GetSecret:input_type -> gophkeeper.GetSecretRequest
	6, // 5: gophkeeper.SecretService.DeleteSecret:input_type -> gophkeeper.DeleteSecretRequest
	1, // 6: gophkeeper.SecretService.CreateSecret:output_type -> gophkeeper.CreateSecretResponse
	3, // 7: gophkeeper.SecretService.GetSecrets:output_type -> gophkeeper.GetSecretsResponse
	5, // 8: gophkeeper.SecretService.GetSecret:output_type -> gophkeeper.GetSecretResponse
	7, // 9: gophkeeper.SecretService.DeleteSecret:output_type -> gophkeeper.DeleteSecretResponse
	6, // [6:10] is the sub-list for method output_type
	2, // [2:6] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_secret_proto_init() }
func file_secret_proto_init() {
	if File_secret_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_secret_proto_rawDesc), len(file_secret_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_secret_proto_goTypes,
		DependencyIndexes: file_secret_proto_depIdxs,
		MessageInfos:      file_secret_proto_msgTypes,
	}.Build()
	File_secret_proto = out.File
	file_secret_proto_goTypes = nil
	file_secret_proto_depIdxs = nil
}
