syntax = "proto3";

package gophkeeper;

option go_package = "gophkeeper/server/proto/gophkeeper";

// SecretService — сервис работы с секретами
service SecretService {
  rpc CreateSecret(CreateSecretRequest) returns (CreateSecretResponse);
  rpc GetSecrets(GetSecretsRequest) returns (GetSecretsResponse);
  rpc GetSecret(GetSecretRequest) returns (GetSecretResponse);
  rpc DeleteSecret(DeleteSecretRequest) returns (DeleteSecretResponse);
}



message CreateSecretRequest {
  string type     = 1;
  string title    = 2;
  string data     = 3;
  string metadata = 4;
}

message CreateSecretResponse {
  string secret_id = 1;
  string message   = 2;
}

message GetSecretsRequest {}

message GetSecretsResponse {
  repeated SecretData secrets = 1;
}

message GetSecretRequest {
  string secret_id = 1;
}

message GetSecretResponse {
  SecretData secret = 1;
}

message DeleteSecretRequest {
  string secret_id = 1;
}

message DeleteSecretResponse {
  string message = 1;
}

// Общая структура секрета
message SecretData {
  string id         = 1;
  string user_id    = 2;
  string type       = 3;
  string title      = 4;
  string data       = 5;
  string metadata   = 6;
  string created_at = 7;
  string updated_at = 8;
}